#! /bin/sh

sxhkd &
dunst &

# polybar

~/.config/polybar/launch.sh &

# compositing and wallpaper

picom &
feh --bg-fill ~/Downloads/94q1v1r2q8p71.png

bspc monitor -d 一 二 三 四 五

bspc config border_width        5
bspc config top_padding         5
bspc config window_gap          10	
bsp config presel_feedback_color "#ffffff"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### BSPWM coloring ####
bspc config normal_border_color              "#A020F0"
bspc config active_border_color              "#A020F0"
bspc config focused_border_color             "#A020F0"
bspc config presel_feedback_color            "#A020F0"
bspc config urgent_border_color              "#A020F0"
